version: '3.7'
services:
  nvidia-gpu-exporter:
    image: nvidia-gpu-exporter:1.0
    environment:
      LOG_LEVEL: debug
      PORT: 9500
      HOST: 0.0.0.0
      INTERVAL: 5
    ports:
      - 9500:9500
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
