metrics:
  - name: gpu_id_metric
    type: gauge
    help: "ID of the GPU."
    labels:
      label1: gpu_name
      label2: gpu_temperature_threshold
      label3: gpu_memory_clock_max
      label4: gpu_cores
      label5: gpu_id
      label6: gpu_driver_version
      label7: gpu_cuda_version


  - name: gpu_name
    type: gauge
    help: "Name of the GPU."
    labels:
      label1: gpu_name

  - name: gpu_gpu_utilization
    type: gauge
    help: "GPU utilization in percent."
    labels:
      label1: gpu_id
      label2: gpu_name

  - name: gpu_mem_utilization
    type: gauge
    help: "GPU memory utilization in percent."
    labels:
      label1: gpu_id
      label2: gpu_name

  - name: gpu_temperature
    type: gauge
    help: "Temperature of the GPU in degrees Celsius."
    labels:
      label1: gpu_id
      label2: gpu_name
      label3: gpu_temperature_threshold

  - name: gpu_power_usage
    type: gauge
    help: "Power usage of the GPU in watts."
    labels:
      label1: gpu_id
      label2: gpu_name

  - name: gpu_running_process
    type: gauge
    help: "Number of running processes on the GPU."
    labels:
      label1: gpu_id
      label2: gpu_name

  - name: gpu_memory_total
    type: gauge
    help: "Total memory of the GPU in MiB."
    labels:
      label1: gpu_id
      label2: gpu_name

  - name: gpu_memory_used
    type: gauge
    help: "Used memory of the GPU in MiB."
    labels:
      label1: gpu_id
      label2: gpu_name

  - name: gpu_memory_free
    type: gauge
    help: "Free memory of the GPU in MiB."
    labels:
      label1: gpu_id
      label2: gpu_name

  - name: gpu_p_state
    type: gauge
    help: "P-State of the GPU."
    labels:
      label1: gpu_id
      label2: gpu_name

  - name: gpu_memory_clock
    type: gauge
    help: "Memory clock of the GPU in MHz."
    labels:
      label1: gpu_id
      label2: gpu_name
      label3: gpu_memory_clock_max

  - name: gpu_ecc_corrected_errors
    type: gauge
    help: "Number of corrected ECC errors."
    labels:
      label1: gpu_id
      label2: gpu_name

  - name: gpu_ecc_uncorrected_errors
    type: gauge
    help: "Number of uncorrected ECC errors."
    labels:
      label1: gpu_id
      label2: gpu_name